export const ADD_ARTICLE = 'ADD_ARTICLE';
export const INC_COUNTER = 'INC_COUNTER';
export const DEC_COUNTER = 'DEC_COUNTER';
export const DATA_LOADED = 'DATA_LOADED';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCSESS = 'REGISTER_SUCCSESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCSESS = 'LOGIN_SUCCSESS';
export const LOGIN_ERROR = 'LOGLOGIN_ERRORIN';
export const CLEAR_LOGIN_DATA = 'CLEAR_LOGIN_DATA';

export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCSESS = 'AUTH_SUCCSESS';
export const AUTH_ERROR = 'AUTH_ERROR';

export const TRANS_REQUEST = 'TRANS_REQUEST';
export const TRANS_SUCCSESS = 'TRANS_SUCCSESS';
export const TRANS_ERROR = 'TRANS_ERROR';

export const TRANS_UPDATE_REQUEST = 'TRANS_UPDATE_REQUEST';
export const TRANS_UPDATE_SUCCSESS = 'TRANS_UPDATE_SUCCSESS';
export const TRANS_UPDATE_ERROR = 'TRANS_UPDATE_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const UPGRADE_REQUEST = 'UPGRADE_REQUEST';
export const UPGRADE_SUCCSESS = 'UPGRADE_SUCCSESS';
export const UPGRADE_ERROR = 'UPGRADE_ERROR';

export const OPEN_MODAL_REGISTER = 'OPEN_MODAL_REGISTER';
export const CLOSE_MODAL_REGISTER = 'CLOSE_MODAL_REGISTER';
export const OPEN_MODAL_LOGIN = 'OPEN_MODAL_LOGIN';
export const CLOSE_MODAL_LOGIN = 'CLOSE_MODAL_LOGIN';

export const GET_TYPES_REQUEST = 'GET_TYPES_REQUEST';
export const GET_TYPES_SUCCSESS = 'GET_TYPES_SUCCSESS';
export const GET_TYPES_ERROR = 'GET_TYPES_ERROR';

export const POST_ARTIST_ERROR = 'POST_ARTIST_ERROR';
export const POST_ARTIST_REQUEST = 'POST_ARTIST_REQUEST';
export const POST_ARTIST_SUCCSESS = 'POST_ARTIST_SUCCSESS';
export const CLEAR_ERROR_ARTIST = 'CLEAR_ERROR_ARTIST';
export const CLEAR_MESSAGE_ARTIST = 'CLEAR_MESSAGE_ARTIST';

export const GET_ARTIST_ERROR = 'GET_ARTIST_ERROR';
export const GET_ARTIST_REQUEST = 'GET_ARTIST_REQUEST';
export const GET_ARTIST_SUCCSESS = 'GET_ARTIST_SUCCSESS';

export const GET_SONGS_REQUEST = 'GET_SONGS_REQUEST';
export const GET_SONGS_SUCCSESS = 'GET_SONGS_SUCCSESS';
export const GET_SONGS_ERROR = 'GET_SONGS_ERROR';

export const POST_SONGS_REQUEST = 'POST_SONGS_REQUEST';
export const POST_SONGS_SUCCSESS = 'POST_SONGS_SUCCSESS';
export const POST_SONGS_ERROR = 'POST_SONGS_ERROR';

export const GET_DETAIL_SONG_ERROR = 'GET_DETAIL_SONG_ERROR';
export const GET_DETAIL_SONG_REQUEST = 'GET_DETAIL_SONG_REQUEST';
export const GET_DETAIL_SONG_SUCCSESS = 'GET_DETAIL_SONG_SUCCSESS';
export const CLEAR_DETAIL_SONG_SUCCSESS = 'CLEAR_DETAIL_SONG_SUCCSESS';
