export const ADD_ARTICLE = 'ADD_ARTICLE';
export const INC_COUNTER = 'INC_COUNTER';
export const DEC_COUNTER = 'DEC_COUNTER';
export const DATA_LOADED = 'DATA_LOADED';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCSESS = 'REGISTER_SUCCSESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCSESS = 'LOGIN_SUCCSESS';
export const LOGIN_ERROR = 'LOGLOGIN_ERRORIN';
export const CLEAR_LOGIN_DATA = 'CLEAR_LOGIN_DATA';

export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCSESS = 'AUTH_SUCCSESS';
export const AUTH_ERROR = 'AUTH_ERROR';

export const TRANS_REQUEST = 'TRANS_REQUEST';
export const TRANS_SUCCSESS = 'TRANS_SUCCSESS';
export const TRANS_ERROR = 'TRANS_ERROR';

export const TRANS_UPDATE_REQUEST = 'TRANS_UPDATE_REQUEST';
export const TRANS_UPDATE_SUCCSESS = 'TRANS_UPDATE_SUCCSESS';
export const TRANS_UPDATE_ERROR = 'TRANS_UPDATE_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const UPGRADE_REQUEST = 'UPGRADE_REQUEST';
export const UPGRADE_SUCCSESS = 'UPGRADE_SUCCSESS';
export const UPGRADE_ERROR = 'UPGRADE_ERROR';

export const OPEN_MODAL_REGISTER = 'OPEN_MODAL_REGISTER';
export const CLOSE_MODAL_REGISTER = 'CLOSE_MODAL_REGISTER';
export const OPEN_MODAL_LOGIN = 'OPEN_MODAL_LOGIN';
export const CLOSE_MODAL_LOGIN = 'CLOSE_MODAL_LOGIN';

export const GET_SONGS_REQUEST = 'GET_SONGS_REQUEST';
export const GET_SONGS_SUCCSESS = 'GET_SONGS_SUCCSESS';
export const GET_SONGS_ERROR = 'GET_SONGS_ERROR';

//  HAPUS KALO SUDAH BERES
export const OPEN_MODAL_ADD_EPISODE = 'OPEN_MODAL_ADD_EPISODE';
export const CLOSE_MODAL_ADD_EPISODE = 'CLOSE_MODAL_ADD_EPISODE';

export const GET_MOVIES_REQUEST = 'GET_MOVIES_REQUEST';
export const GET_MOVIES_SUCCSESS = 'GET_MOVIES_SUCCSESS';
export const GET_MOVIES_ERROR = 'GET_MOVIES_ERROR';

export const GET_TV_REQUEST = 'GET_TV_REQUEST';
export const GET_TV_SUCCSESS = 'GET_TV_SUCCSESS';
export const GET_TV_ERROR = 'GET_TV_ERROR';

export const GET_DETAIL_MOVIE_REQUEST = 'GET_DETAIL_MOVIE_REQUEST';
export const GET_DETAIL_MOVIE_SUCCSESS = 'GET_DETAIL_MOVIE_SUCCSESS';
export const GET_DETAIL_MOVIE_ERROR = 'GET_DETAIL_MOVIE_ERROR';

export const GET_EPISODE_BY_MOVIE_REQUEST = 'GET_EPISODE_BY_MOVIE_REQUEST';
export const GET_EPISODE_BY_MOVIE_SUCCSESS = 'GET_EPISODE_BY_MOVIE_SUCCSESS';
export const GET_EPISODE_BY_MOVIE_ERROR = 'GET_EPISODE_BY_MOVIE_ERROR';

export const ADD_EPISODE_REQUEST = 'ADD_EPISODE_REQUEST';
export const ADD_EPISODE_SUCCSESS = 'ADD_EPISODE_SUCCSESS';
export const ADD_EPISODE_ERROR = 'ADD_EPISODE_SUCCSESS';

export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCSESS = 'GET_CATEGORIES_SUCCSESS';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

export const ADD_MOVIE_REQUEST = 'ADD_MOVIE_REQUEST';
export const ADD_MOVIE_SUCCSESS = 'ADD_MOVIE_SUCCSESS';
export const ADD_MOVIE_ERROR = 'ADD_MOVIE_ERROR';

export const ADD_EPISODES_REQUEST = 'ADD_EPISODES_REQUEST';
export const ADD_EPISODES_SUCCSESS = 'ADD_EPISODES_SUCCSESS';
export const ADD_EPISODES_ERROR = 'ADD_EPISODES_ERROR';
